baseURL = "http://example.org/"
languageCode = "en-us"
title = "Eddie Sankey"

[permalinks]
  blog = "/:filename/"

[params]
homeText = "You just made a Hugo blog from scratch."
css_sheets = ["css/styles.css"]

[menu]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 3
    [[menu.main]]
    name = "Dummy1"
    url = "/dummy1/"
    weight = 4
    [[menu.main]]
    name = "Dummy2"
    url = "/dummy2/"
    weight = 5
    [[menu.main]]
    name = "Dummy3"
    url = "/dummy3/"
    weight = 6

    [[menu.socials]]
    name = "Github"
    pre = "icons/github.svg"
    url = "https://github.com/eddiesankey"
    weight = 1
    [[menu.socials]]
    name = "LinkedIn"
    pre = "icons/linkedin.svg"
    url = "https://www.linkedin.com/in/edwardsankey/"
    weight = 2