baseURL = "http://example.org/"
languageCode = "en-us"
title = "Eddie Sankey"

[permalinks]
  blog = "/:filename/"

[params]
homeText = "You just made a Hugo blog from scratch."
css_sheets = ["css/styles.css"]

[menu]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3

    [[menu.socials]]
    name = "Github"
    pre = "icons/github.svg"
    url = "https://github.com/eddiesankey"
    weight = 1
    [[menu.socials]]
    name = "LinkedIn"
    pre = "icons/linkedin.svg"
    url = "https://www.linkedin.com/in/edwardsankey/"
    weight = 2